name: mindtrace_ai
description: MindTrace AI - ilmiy asoslangan kognitiv trening ilovasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.38.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^8.1.0
  provider: ^6.1.2
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  firebase_ai: ^3.13.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/standarted.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/standarted.png
